// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvlekwtsusfciadnjfdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2bGVrd3RzdXNmY2lhZG5qZmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTA5MjEsImV4cCI6MjA2MTg4NjkyMX0.cFrFWOlEoqGWOlv13s5NpZrG5cj32o8eNyGwBzaPV9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);